import { cn } from "@/lib/utils"
import { Icons as IconsType } from "@/types"
import { 
  Crown, 
  Loader2, 
  CheckCircle, 
  XCircle, 
  AlertCircle, 
  Info, 
  ChevronDown, 
  ChevronUp, 
  ChevronLeft, 
  ChevronRight,
  Menu,
  X,
  Plus,
  Edit,
  Trash,
  Calendar,
  Target,
  Users,
  FileImage,
  TrendingUp,
  Clock,
  CheckSquare,
  BarChart3,
  FolderOpen,
  Zap,
  Settings,
  Flag,
  Search,
  Filter,
  MoreHorizontal,
  CheckCircle2,
  Circle,
  Pause,
  DollarSign,
  User
} from "lucide-react"

export const Icons = {
  crown: Crown,
  spinner: Loader2,
  checkCircle: CheckCircle,
  xCircle: XCircle,
  alertCircle: AlertCircle,
  info: Info,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  menu: Menu,
  x: X,
  plus: Plus,
  edit: Edit,
  trash: Trash,
  calendar: Calendar,
  target: Target,
  users: Users,
  fileImage: FileImage,
  trendingUp: TrendingUp,
  clock: Clock,
  checkSquare: CheckSquare,
  barChart3: BarChart3,
  folderOpen: FolderOpen,
  zap: Zap,
  settings: Settings,
  flag: Flag,
  search: Search,
  filter: Filter,
  moreHorizontal: MoreHorizontal,
  checkCircle2: CheckCircle2,
  circle: Circle,
  pause: Pause,
  dollarSign: DollarSign,
  user: User,
}

export type Icon = typeof Icons

export function Icon({ className, ...props }: React.SVGProps<SVGSVGElement>) {
  return <svg className={cn("h-4 w-4", className)} {...props} />
}